import type { ClientDirectoryRecord } from "@/types/clients";

export const clientDirectoryDemoData: ClientDirectoryRecord[] = [
  {
    id: "emily-carter",
    name: "Emily Carter",
    initials: "EC",
    primaryService: "Lashes",
    status: "ready",
    clientType: "New client",
    lastVisit: "First visit",
    nextAppointment: "Today",
    nextAppointmentTime: "2:00 PM",
    context: "Client experience complete",
  },
  {
    id: "sarah-cole",
    name: "Sarah Cole",
    initials: "SC",
    primaryService: "Brows",
    status: "waiting",
    clientType: "Returning client",
    lastVisit: "6 weeks ago",
    nextAppointment: "Today",
    nextAppointmentTime: "4:30 PM",
    context: "2 items outstanding",
  },
  {
    id: "naomi-brooks",
    name: "Naomi Brooks",
    initials: "NB",
    primaryService: "Makeup",
    status: "ready",
    clientType: "Returning client",
    lastVisit: "3 months ago",
    nextAppointment: "Today",
    nextAppointmentTime: "6:00 PM",
    context: "Client experience complete",
  },
  {
    id: "ava-james",
    name: "Ava James",
    initials: "AJ",
    primaryService: "Lashes",
    status: "complete",
    clientType: "Returning client",
    lastVisit: "Yesterday",
    nextAppointment: null,
    nextAppointmentTime: null,
    context: "Visit complete",
  },
  {
    id: "nina-patel",
    name: "Nina Patel",
    initials: "NP",
    primaryService: "Brows",
    status: "complete",
    clientType: "Returning client",
    lastVisit: "Monday",
    nextAppointment: null,
    nextAppointmentTime: null,
    context: "Visit complete",
  },
  {
    id: "lucy-hall",
    name: "Lucy Hall",
    initials: "LH",
    primaryService: "Lashes",
    status: "draft",
    clientType: "Returning client",
    lastVisit: "Friday",
    nextAppointment: "Not scheduled",
    nextAppointmentTime: null,
    context: "Client experience draft",
  },
];
